name: ds_json
description: Deadly simple json object accessor
version: 1.1.0
repository: https://github.com/uac-nhan-nguyen/ds_json
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: ^1.22.1

